version: '2.2'

volumes:
  octoprint:

services:
  octoprint_mini:
    restart: unless-stopped
    image: octoprint/octoprint
    ports:
      - 5000:80
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - "your media"/octoprint:/home/octoprint

  mjpg-streamer:
    restart: unless-stopped
    image: openhorizon/mjpg-streamer-pi3
    command: ./mjpg_streamer -o "output_http.so -w ./www" -i "input_uvc.so -r 1280x720 -d /dev/video0 -f 30"
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 5001:8080
